### ISSUE TITLE
希望添加读取help时可以读取图片

### ISSUE THREAD

**Issue by doiss** [SonderXiaoming/autohelp#10]
![QQ图片20220529233001](https://user-images.githubusercontent.com/97965580/170877540-744e59b4-1ba1-4ac6-b6dc-74a181c0ccbd.png)

**Comment by SonderXiaoming** [comment]
你图片用网络地址，不要用本地地址就行。类似这种的https://sm.ms/image/QlS4piWXw5rZO3D

**Comment by doiss** [comment]
> 你图片用网络地址，不要用本地地址就行。类似这种的 https://sm.ms/image/QlS4piWXw5rZO3D

🆗，感谢大佬
