### ISSUE TITLE
无法显示表格

### ISSUE THREAD

**Issue by int-PP** [SonderXiaoming/autohelp#15]
![}P5WSBC }RWJ8~T}52EHP75](https://user-images.githubusercontent.com/105854929/191009098-4c6dbec2-829c-4a9d-a88b-2452391bf223.png)
使用details做下拉菜单之后表格无法显示

**Comment by int-PP** [comment]
有什么解决办法吗？
![GI)IS`G`3P( G3K%ZIET9}6](https://user-images.githubusercontent.com/105854929/191009515-58163a27-8bb2-4c94-8aba-0a128f64301d.jpg)

**Comment by SonderXiaoming** [comment]
用service mod，我记得马娘插件适配了我的autohelp

**Comment by int-PP** [comment]
不知道为啥图片经常不显示，所以写了个文字的。service mod是什么？
![](https://user-images.githubusercontent.com/105854929/191009515-58163a27-8bb2-4c94-8aba-0a128f64301d.jpg)

**Comment by SonderXiaoming** [comment]
![image](https://user-images.githubusercontent.com/98363578/191414249-48abedae-26da-4605-b87c-c421e14e3d97.png)
1就是service mod，读取service中的help

**Comment by int-PP** [comment]
用过这个经常显示空白
![I9~NUG)JN N6{F} @T1OEMP](https://user-images.githubusercontent.com/105854929/191415101-5262e8bb-25ec-45b6-8850-e27fb4d0e3e6.jpg)
然后才改写文字，然后发现下拉菜单会不显示表格

**Comment by SonderXiaoming** [comment]
空白建议跑去和马娘插件作者交流，他不是号称适配过了嘛（笑）
下拉菜单可能代码有点问题，Markdown我不是很熟

**Comment by int-PP** [comment]
草，隔壁已经打算换图床或者改本地了hhh
