### ISSUE TITLE
部署后网页端无法读取Readme

### ISSUE THREAD

**Issue by 1529960009** [SonderXiaoming/autohelp#4]
![QQ截图20220515141347](https://user-images.githubusercontent.com/45947734/168459765-190ac44c-6df3-492e-b587-b03ca8f45906.png)
![QQ截图20220515141225](https://user-images.githubusercontent.com/45947734/168459767-573932b6-9f6f-434b-ab39-f27540bb8bb1.png)

**Comment by SonderXiaoming** [comment]
按ctrl+shift+i，再点控制台，我看一下报错

**Comment by 1529960009** [comment]
![QQ截图20220516235704](https://user-images.githubusercontent.com/45947734/168634597-a1a78add-cbf0-44dd-9314-b80294103e0f.png)

**Comment by 1529960009** [comment]
![QQ截图20220516235704](https://user-images.githubusercontent.com/45947734/168634660-8a076d0a-6fd6-4ee3-87da-03717680f124.png)

**Comment by 1529960009** [comment]
我自己的BOT端口是7777，看控制台，Json端口和我BOT端口不符合，这个8080是怎么获得的鸭

**Comment by 1529960009** [comment]
![QQ截图20220517000423](https://user-images.githubusercontent.com/45947734/168635933-9df3181a-bbeb-4c2a-b0fb-16a0966357f5.png)
我看了一下help.html中有8080端口，把8080端口改为我自己端口7777就正常了

**Comment by SonderXiaoming** [comment]
确实没考虑到端口问题，默认8080了
