### ISSUE TITLE
部署后无法通过公网ip:端口/bot/help实现访问【已解决】

### ISSUE THREAD

**Issue by SanaChitose** [SonderXiaoming/autohelp#5]
部署成功且可以通过127.0.0.1:8080/bot/help实现本地访问和调试：
![图片](https://user-images.githubusercontent.com/102790983/168541246-398067f6-b096-41e7-ad92-35d74e6b3269.png)
但通过公网ip构造的url则提示超时：
![图片](https://user-images.githubusercontent.com/102790983/168542761-807ecbef-14d6-46da-8864-1926db2a99a8.png)
在部署bot的服务器本机上访问公网ip构造的url时提示拒绝访问请求（右边的标签是通过127.0.0.1实现的成功访问）：
![图片](https://user-images.githubusercontent.com/102790983/168542234-1e513110-a1a6-4934-b149-cc13229414e1.png)
服务器是腾讯云，防火墙准入规则已经添加8080端口：
![图片](https://user-images.githubusercontent.com/102790983/168542538-1abf0fbc-a676-4102-a086-f65f24633a7a.png)
希望大佬解惑！

**Comment by SanaChitose** [comment]
> 部署成功且可以通过127.0.0.1:8080/bot/help实现本地访问和调试： ![图片](https://user-images.githubusercontent.com/102790983/168541246-398067f6-b096-41e7-ad92-35d74e6b3269.png) 但通过公网ip构造的url则提示超时： ![图片](https://user-images.githubusercontent.com/102790983/168542761-807ecbef-14d6-46da-8864-1926db2a99a8.png) 在部署bot的服务器本机上访问公网ip构造的url时提示拒绝访问请求（右边的标签是通过127.0.0.1实现的成功访问）： ![图片](https://user-images.githubusercontent.com/102790983/168542234-1e513110-a1a6-4934-b149-cc13229414e1.png) 服务器是腾讯云，防火墙准入规则已经添加8080端口： ![图片](https://user-images.githubusercontent.com/102790983/168542538-1abf0fbc-a676-4102-a086-f65f24633a7a.png) 希望大佬解惑！

补充一下，将文件中的"127.0.0.1"替换为公网ip后打开的127.0.0.1:8080/bot/help界面疑似无法读取readme.md
![图片](https://user-images.githubusercontent.com/102790983/168544579-0956ea11-7d83-4cd4-95e6-af1924373da3.png)

**Comment by SonderXiaoming** [comment]
我自己服务器基本上属于裸奔，不太清楚你的情况
可以尝试以下解决方案
1.在\hoshino\config中的__bot__.py中，把host从127.0.0.1改为0.0.0.0
2.腾讯云防火墙添加规则，选择all
3.关闭windows防火墙
（无论成功与否，记得反馈给我）

**Comment by SanaChitose** [comment]
> 我自己服务器基本上属于裸奔，不太清楚你的情况 可以尝试以下解决方案 1.在\hoshino\config中的__bot__.py中，把host从127.0.0.1改为0.0.0.0 2.腾讯云防火墙添加规则，选择all 3.关闭windows防火墙 （无论成功与否，记得反馈给我）

可否告知如何修改网页端口？我个人推测可能和hoshino默认监听的端口为8080有关

**Comment by SonderXiaoming** [comment]
我就是8080，没有任何问题
建议先照我说的尝试
如果要改端口在\hoshino\config中的__bot__.py中修改port，然后help.html修改8080字段（可能有未知问题）

**Comment by SanaChitose** [comment]
> 我就是8080，没有任何问题 建议先照我说的尝试 如果要改端口在\hoshino\config中的__bot__.py中修改post，然后help.html修改8080字段（可能有未知问题）

控制变量后发现需要hoshino开放公网访问（即在\hoshino\config中的__bot__.py中，把host从127.0.0.1改为0.0.0.0）
但初步感觉这样不太安全，我个人再研究一下更改端口能不能实现吧
有进展会通知您

**Comment by SonderXiaoming** [comment]
如果要安全可以参考https://yobot.win/usage/web-mode/
使用代理
或者使用樱花frp，花生壳什么的内网穿透

**Comment by SanaChitose** [comment]
捉个虫，原生hoshino的__bot__.py中端口字段为port而非post（
![图片](https://user-images.githubusercontent.com/102790983/168705578-9545b4aa-97da-4112-a440-69962d1c61a0.png)

**Comment by SonderXiaoming** [comment]
寄，打错了
