### ISSUE TITLE
一些小小想法

### ISSUE THREAD

**Issue by Lanly109** [SonderXiaoming/autohelp#6]
感谢dalao提供的轮子，今天尝试了进行部署，想到了点改进的方向
1. 插件帮助文案的渲染，感觉改成服务端渲染好一点？一方面减少了二次请求和客户端渲染，另一方面做到了真正的黑名单，在服务器渲染时就把黑名单里的插件去掉。因为现在这个黑名单实际上人家还是可以查看`json`文案然后访问对应的`url`得到黑名单插件的`readme`。
2. 帮助文案是不是取服务`Service`的`help`文案好点？当然我不清楚起初是不是因为这个`help`文案混乱才用`readme`作为帮助文案。但因为`readme`有好些都不是给用户阅读的，而是维护人员，而每个插件单独建一个`userreadme`有点小麻烦；并且还有个问题就是可能一个`module`的文件夹里有不止一个插件，但它们只能共享一个`userreadme`。还有就是文件夹名也不一定是`service`名，用户管理员在自己启动禁用插件时还是不容易找到帮助文案对应的`service`名字。

第一点的改进就把要渲染的内容（插件名和插件帮助文案）变量传入`render_template`函数里，`help.html`解析该变量就可以了。
第二点的改进，在`Service`类里有个`get_loaded_services`类可以获取已加载的插件，包括其`name`和`help`。当然可以将`help` 渲染成`html`然后嵌入到网页里，这样帮助文案里显示的插件名字就是`service name`。

我自己对这两点改进，但由于我对`JQuery UI库`不太熟悉，在修改后出现了折叠效果不符合预期行为的问题（折叠动画不是从下往上慢慢闭合，而是直接闭合后往下展开一点点，如下动图所示），目前还在研究原因中。

![DyhvP.gif](https://s1.328888.xyz/2022/05/17/DyhvP.gif)

如果需要，我可以把我改的pr上来。

**Comment by SonderXiaoming** [comment]
pr最好
（我起初建立这个就是对这些各种仓库的help不信任）
第二点的话，想法不错，可以做一下改动，优先userreadme，然后读取help，最后没办法再readme

**Comment by SonderXiaoming** [comment]
顺带一提
我觉得应该还是以文件夹分比较好，因为service也是纯看仓库，可能有些仓库service还比较多（比如咖啡佬的推特转发），
但读取service的help是不错的，可以一个文件夹里面service的help合并在一起。
至于一个module的文件夹里有不止一个插件（应该至少是一大类，除非你插件乱装）
对于用户管理员在自己启动禁用插件时还是不容易找到帮助文案对应的service名字这个问题，可以在多一行service名在渲染时加上即可（我自己是不希望用户管理员自己随便乱开关插件）
其他我没意见，你直接pr
