### ISSUE TITLE
自定义网页背景图片

### ISSUE THREAD

**Issue by SanaChitose** [SonderXiaoming/autohelp#9]
翻了资源库唯独没有看到猫猫这张图，因此无法简单粗暴的平替，本人对前端一窍不通，不知道大佬是否方便提供这一选项
（因为bot发展到现在已经和pcr没啥关系了）
如果不好提供，请大佬直接关闭，打扰大佬了

**Comment by SonderXiaoming** [comment]
在[static](https://github.com/SonderXiaoming/autohelp/tree/main/static)里pcr中的css可以找到“style1”和”style2”两个文件中有个
https://pic1.zhimg.com/v2-607f7a8546e9fbb98960f7e5bb09217e_r.jpg?source=1940ef5c
的url，这就是猫猫图片的来源
（猫猫这么好看，你居然要换）

**Comment by SanaChitose** [comment]
感谢大佬！
